### ISSUE TITLE
ERROR Unmaintained in sdk53

### ISSUE THREAD

**Issue by ingabelsierra** [galio-org/galio#268]
Validate packages against React Native Directory package metadata
The following issues were found when validating your dependencies against React Native Directory:
  Unmaintained: galio-framework
Advice:
Use libraries that are actively maintained and support the New Architecture. Find alternative libraries with https://reactnative.directory.

**Comment by ingabelsierra** [comment]
I would like to know if you are going to update the library to be compatible with SDK53 and not have to migrate to another framework. I look forward to your response.

**Comment by Salmankhan033** [comment]
+1

**Comment by baseley** [comment]
I'm working on updating the framework to the latest version of react and react native. I hope to come up with a new PR this week.

**Comment by noranb** [comment]
I am trying to decide if I need to switch to another set of controls or will these controls be updated to the latest version of react and react native?
Thanks

**Comment by noranb** [comment]
@ingabelsierra What framework are you switching to?

**Comment by ingabelsierra** [comment]
I'm waiting for Mr. @baseley  update.

**Comment by ingabelsierra** [comment]
As a last resort, if they don't update the project, I'm considering https://www.npmjs.com/package/react-native-paper

**Comment by baseley** [comment]
@ingabelsierra  @noranb please check that PR: https://github.com/galio-org/galio/pull/269
If is working, we can start to build new version for that framework.

**Comment by marqbeniamin** [comment]
@ingabelsierra @noranb @Salmankhan033 we have a beta version here: https://www.npmjs.com/package/galio-framework/v/0.9.1-beta.3, the stable version comes tomorrow

**Comment by ingabelsierra** [comment]
> [@ingabelsierra](https://github.com/ingabelsierra) [@noranb](https://github.com/noranb) [@Salmankhan033](https://github.com/Salmankhan033) we have a beta version here: https://www.npmjs.com/package/galio-framework/v/0.9.1-beta.3, the stable version comes tomorrow

hi friends, I tried the new version 0.92 in sdk 53 
It created a conflict. share the errors screens

<img width="1821" height="366" alt="Image" src="https://github.com/user-attachments/assets/b3370f4c-2a61-416a-9ca9-ad5df05f5a13" />

![Image](https://github.com/user-attachments/assets/63e3abe8-7096-421a-a764-c2dc0707469e)

<img width="930" height="191" alt="Image" src="https://github.com/user-attachments/assets/33d7bdef-7cd4-45e8-a284-99b0d9b421fa" />

my package.json

 "dependencies": {
   "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/datetimepicker": "8.4.1",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-picker/picker": "2.11.1",
    "@react-navigation/drawer": "^6.6.4",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.8",
    "@react-navigation/stack": "^6.3.18",
    "axios": "^1.6.6",
    "expo": "^53.0.16",
    "expo-file-system": "~18.1.11",
    "expo-intent-launcher": "~12.1.5",
    "expo-local-authentication": "~16.0.5",
    "expo-splash-screen": "~0.30.9",
    "expo-status-bar": "~2.2.3",
    "formik": "^2.2.9",
    **"galio-framework": "^0.9.2",**
    "lottie-react-native": "7.2.2",
    "prop-types": "^15.8.1",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-raw-bottom-sheet": "^3.0.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-web": "^0.20.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@types/react": "~19.0.10",
    "@types/react-native": "~0.70.6",
    "typescript": "~5.8.3"
  },

**Comment by marqbeniamin** [comment]
> hi friends, I tried the new version 0.92 in sdk 53 It created a conflict. share the errors screens

Clean your project and try again:

rm -rf node_modules
npm install

**Comment by marqbeniamin** [comment]
@ingabelsierra I omitted the "dist" folder from the release, you can try again with V0.9.3

**Comment by ingabelsierra** [comment]
hi @marqbeniamin good day, This version 0.9.3 is creating a strange conflict with the @react-navigation/native and @react-navigation/stack libraries.

<img width="894" height="340" alt="Image" src="https://github.com/user-attachments/assets/b0530ba1-8f59-4996-8d43-70ddd2a5756d" />


with the version 0.9.3 it looks like this
![Image](https://github.com/user-attachments/assets/c379eb9c-8ce7-49ff-a433-79a40a83693c)


and with the version 0.8.0 it looks like this

![Image](https://github.com/user-attachments/assets/5170b1ba-27e7-4054-9d49-41c2cb5fc142)

**Comment by ingabelsierra** [comment]
Good Day

<img width="1684" height="763" alt="Image" src="https://github.com/user-attachments/assets/5ca405a1-c396-4844-84e7-67af7daaf5df" />


I still haven't been able to update to the SDK53 version and the error persists with the framework.

**Comment by ingabelsierra** [comment]
@marqbeniamin @baseley 
If you need more information to solve and update to the SDK53 version, let me know, thanks.

**Comment by marqbeniamin** [comment]
can you try with v0.9.4?
It should work now.

**Comment by ingabelsierra** [comment]
good day, I have installed this new version and the error persists.

<img width="1652" height="752" alt="Image" src="https://github.com/user-attachments/assets/49f4cdca-0076-45f0-ba4a-2f5247801700" />

**Comment by ingabelsierra** [comment]
Hello, of course, I'm attaching the package.json, the error seen in the code, and the screenshot of the conflict that Galio is creating with the header in the navigation. If you need more information or anything else that can help you solve the bug, let me know. Thanks.

<img width="1706" height="909" alt="Image" src="https://github.com/user-attachments/assets/1127cfe8-da00-4ab7-9ff6-0e6d2295ce4a" />

```typescript
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import { Block, GalioProvider } from "galio-framework";
import { nowTheme } from "./constants";

import LoginScreen from "./screens/Navigation/LoginScreen";
import DrawerNavigationRoutes from "./screens/Navigation/DrawerNavigationRoutes";

//Home
import NuevaCotizacionScreen from "./screens/Screens/Dasboard/NuevaCotizacion";
import GuardarCotizacionScreen from "./screens/Screens/Dasboard/GuardarCotizacion";
import NuevoClienteScreen from "./screens/Screens/Dasboard/NuevoCliente";
import PropietariosScreen from "./screens/Screens/Dasboard/Propietarios";

import useCachedResources from "./hooks/useCachedResources";

const Stack = createStackNavigator();

const Auth = () => {
  return (
    <Stack.Navigator initialRouteName="LoginScreen">
      <Stack.Screen
        name="LoginScreen"
        component={LoginScreen}
        options={{ headerShown: false }}
      />
    </Stack.Navigator>
  );
};

export default function App() {
  const isLoadingComplete = useCachedResources();

  if (!isLoadingComplete) {
    return null;
  } else {
    return (
      <NavigationContainer>
        <GalioProvider theme={nowTheme}>
          <Block flex>
            <Stack.Navigator initialRouteName="Auth">
              <Stack.Screen
                name="Auth"
                component={Auth}
                options={{ headerShown: false }}
              />

              <Stack.Screen
                name="DrawerNavigationRoutes"
                component={DrawerNavigationRoutes}
                options={{ headerShown: false }}
              />

              {/**Home*/}

              <Stack.Screen
                name="NuevaCotizacion"
                component={NuevaCotizacionScreen}
                options={{
                  headerShown: true,
                  headerStyle: {
                    backgroundColor: nowTheme.COLORS.NAV,
                  },
                  headerTintColor: "#fff",
                  headerTitle: "NUEVA COTIZACIÓN",
                  headerTitleStyle: {
                    fontFamily: "montserrat-bold",
                    fontSize: 16,
                  },
                }}
              />

              <Stack.Screen
                name="GuardarCotizacion"
                component={GuardarCotizacionScreen}
                options={{
                  headerShown: true,
                  headerStyle: {
                    backgroundColor: nowTheme.COLORS.NAV,
                  },
                  headerTintColor: "#fff",
                  headerTitle: "GENERAR COTIZACIÓN",
                  headerTitleStyle: {
                    fontFamily: "montserrat-bold",
                    fontSize: 16,
                  },
                }}
              />

              <Stack.Screen
                name="NuevoCliente"
                component={NuevoClienteScreen}
                options={{
                  headerShown: true,
                  headerStyle: {
                    backgroundColor: nowTheme.COLORS.NAV,
                  },
                  headerTintColor: "#fff",
                  headerTitle: "CREAR NUEVO CLIENTE",
                  headerTitleStyle: {
                    fontFamily: "montserrat-bold",
                    fontSize: 16,
                  },
                }}
              />

              <Stack.Screen
                name="Propietarios"
                component={PropietariosScreen}
                options={{
                  headerShown: true,
                  headerStyle: {
                    backgroundColor: nowTheme.COLORS.NAV,
                  },
                  headerTintColor: "#fff",
                  headerTitle: "PROPIETARIOS",
                  headerTitleStyle: {
                    fontFamily: "montserrat-bold",
                    fontSize: 16,
                  },
                }}
              />
            </Stack.Navigator>
          </Block>
        </GalioProvider>
      </NavigationContainer>
    );
  }
}

``` 

my package.json

{
  "name": "colacoradores",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "2.1.2",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-picker/picker": "2.11.1",
    "@react-navigation/drawer": "^6.6.4",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.8",
    "@react-navigation/stack": "^6.3.18",
    "axios": "^1.6.6",
    "expo": "^53.0.22",
    "expo-file-system": "~18.1.11",
    "expo-intent-launcher": "~12.1.5",
    "expo-local-authentication": "~16.0.5",
    "expo-splash-screen": "~0.30.9",
    "expo-status-bar": "~2.2.3",
    "formik": "^2.2.9",
    "galio-framework": "^0.9.4",
    "lottie-react-native": "7.2.2",
    "prop-types": "^15.8.1",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-native": "0.79.5",
    "react-native-gesture-handler": "~2.24.0",
    "react-native-raw-bottom-sheet": "^3.0.0",
    "react-native-reanimated": "~3.17.4",
    "react-native-safe-area-context": "5.4.0",
    "react-native-screens": "~4.11.1",
    "react-native-web": "^0.20.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@types/react": "~19.0.10",
    "@types/react-native": "~0.70.6",
    "typescript": "~5.8.3"
  },
  "private": true
}

with the version 0.9.4 it looks like this

<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/b89969f5-6bc9-477c-be83-bc4a45348ed2" />

and with the version 0.8.0 it looks like this

<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/221afef6-0da1-45a6-822d-5bb482bd058c" />

**Comment by ingabelsierra** [comment]
Good day guys, I would like to know how the update is going to fix the bug, if there is anything I can help with, just let me know.
